[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ifitwala_ed"
version = "0.0.1"
authors = [
    { name = "François de Ryckel", email = "f.deryckel@gmail.com"}
]
description = "School management System with integrated Ifitwala Drive file governance"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "holidays>=0.86",
    "jsonschema>=4.0.0",
    "google-cloud-storage>=2.19,<4",
    "PyMuPDF>=1.24,<2",
    "python-magic>=0.4.27,<1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ifitwala_ed*", "ifitwala_drive*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.txt", "*.md", "*.py", "*.yml", "*.yaml", "*.html", "*.js", "*.css", "*.svg"]

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0-dev,<=17.0.0-dev"
